//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShameTheThrones.Models.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int id { get; set; }
        public string title { get; set; }
        public string comment { get; set; }
        public int restroomId { get; set; }
        public int userId { get; set; }
        public Nullable<System.DateTime> deletedAt { get; set; }
        public byte ratingValue { get; set; }
    
        public virtual User User { get; set; }
    }
}
