//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShameTheThrones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public int id { get; set; }
        public string src { get; set; }
        public int parentId { get; set; }
        public byte parentTable { get; set; }
        public Nullable<System.DateTime> deletedAt { get; set; }
    }
}
